### ISSUE TITLE
"REDIS-CLI WAS GOOD IN THE '90S"

### ISSUE THREAD

**Issue by sffc** [Redsmin/website#168]
The first beta release of Redis was not until 2009 though.  Might want to change the slogan?

**Comment by FGRibreau** [comment]
Hello @sffc,

Thank you for your feedback, I see you took it quite literally while people usually took it as an expression.

To be frank, it's the first time someone came with this remark ^^

We won't change the slogan but we definitely agree with your point and wrote this slogan knowingly :)
